




import "./globals.css";

import ThemeClient from "./ThemeClient";

export const metadata = {
  title: 'ایز اسمارت',
  description: 'Generated by create next app',
  manifest:'/manifest.json'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
 {/* <Head/>  */}
      <body>
        <ThemeClient>
          {children}
        </ThemeClient>

      </body>
    </html>
  );
}
