



import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import ThemeClient from "./ThemeClient";
import Head from './head';
export const metadata = {
  title: 'ایز اسمارت',
  description: 'Generated by create next app',
  manifest:'/manifest.json'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
{/* <Head/> */}
      <body className={inter.className}>
        <ThemeClient>
          {children}
        </ThemeClient>

      </body>
    </html>
  );
}
