"use client";

import { Inter } from "next/font/google";
import BottomNavigation from "../components/bottomNavigation";
import FloatingSideBar from "../components/floatingSideBar";
import FloatingButton from "../components/floatingButton";
import "./globals.css";
import { ThemeProvider } from "next-themes";
const inter = Inter({ subsets: ["latin"] });
import "mapbox-gl/dist/mapbox-gl.css";
import axios from 'axios';

axios.defaults.baseURL = 'https://tracker.mmaghsoudi.ir/api/v1/';
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={inter.className}>
      
        <ThemeProvider attribute="class">
        {children}
          <BottomNavigation />

         
        </ThemeProvider>
      </body>
    </html>
  );
}
